name: pyprag
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - audioread
  - blas
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - cycler
  - cython
  - dbus
  - decorator
  - expat
  - fastdtw
  - ffmpeg
  - fontconfig
  - freetype
  - gettext
  - glib
  - gmp
  - gnutls
  - gst-plugins-base
  - gstreamer
  - icu
  - intel-openmp
  - joblib
  - jpeg
  - kiwisolver
  - lame
  - ld_impl_linux-64
  - libblas
  - libcblas
  - libclang
  - libedit
  - libffi
  - libflac
  - libgcc-ng
  - libgfortran-ng
  - libiconv
  - liblapack
  - libllvm8
  - libllvm9
  - libogg
  - libpng
  - librosa
  - libsndfile
  - libstdcxx-ng
  - libuuid
  - libvorbis
  - libxcb
  - libxkbcommon
  - libxml2
  - llvmlite
  - matplotlib
  - matplotlib-base
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - ncurses
  - nettle
  - nspr
  - nss
  - numba
  - numpy
  - numpy-base
  - openh264
  - openssl
  - pcre
  - pip
  - portaudio
  - pthread-stubs
  - pycparser
  - pyparsing
  - pyprof2calltree
  - pyqt
  - pysoundfile
  - python
  - python-dateutil
  - python-sounddevice
  - python_abi
  - qt
  - readline
  - resampy
  - scikit-learn
  - scipy
  - setuptools
  - six
  - sqlite
  - tk
  - tornado
  - wheel
  - x264
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - zlib
  - pip:
    - pyqt5-sip
    - git+https://github.com/pyqtgraph/pyqtgraph@develop
    - pyqtwebengine
    - pyworld
    - tgt
