name: spiny
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.8
  - aom=3.5.0
  - asttokens=2.2.1
  - attr=2.5.1
  - audioread=3.0.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - black=23.1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - cairo=1.16.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - cfgv=3.3.1
  - charset-normalizer=2.1.1
  - click=8.1.3
  - colorama=0.4.6
  - contourpy=1.0.7
  - cryptography=39.0.2
  - cycler=0.11.0
  - cython=0.29.33
  - dbus=1.13.6
  - decorator=5.1.1
  - distlib=0.3.6
  - double-conversion=3.2.0
  - executing=1.2.0
  - expat=2.5.0
  - ffmpeg=5.1.2
  - fftw=3.3.10
  - filelock=3.9.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.39.0
  - freetype=2.12.1
  - gettext=0.21.1
  - glib=2.74.1
  - glib-tools=2.74.1
  - gmp=6.2.1
  - gnutls=3.7.8
  - graphite2=1.3.13
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - gstreamer-orc=0.4.33
  - harfbuzz=6.0.0
  - icu=70.1
  - identify=2.5.20
  - idna=3.4
  - importlib-metadata=6.0.0
  - ipython=8.11.0
  - jack=1.9.22
  - jedi=0.18.2
  - joblib=1.2.0
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lazy_loader=0.1
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.66
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcups=2.3.3
  - libdb=6.2.32
  - libdeflate=1.17
  - libdrm=2.4.114
  - libedit=3.1.20191231
  - libffi=3.4.2
  - libflac=1.4.2
  - libgcc-ng=12.2.0
  - libgcrypt=1.10.1
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.74.1
  - libgomp=12.2.0
  - libgpg-error=1.46
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libllvm15=15.0.7
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpciaccess=0.17
  - libpng=1.6.39
  - libpq=15.2
  - librosa=0.10.0
  - libsndfile=1.2.0
  - libsqlite=3.40.0
  - libstdcxx-ng=12.2.0
  - libsystemd0=252
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libtool=2.4.7
  - libudev1=253
  - libunistring=0.9.10
  - libuuid=2.32.1
  - libva=2.17.0
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp-base=1.3.0
  - libxcb=1.13
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libxslt=1.1.37
  - libzlib=1.2.13
  - llvmlite=0.39.1
  - lz4-c=1.9.4
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mpg123=1.31.2
  - msgpack-python=1.0.5
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - ncurses=6.3
  - nettle=3.8.1
  - nodeenv=1.7.0
  - numba=0.56.4
  - numpy=1.23.5
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=3.1.0
  - p11-kit=0.24.1
  - packaging=23.0
  - parso=0.8.3
  - pathspec=0.11.1
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - pixman=0.40.0
  - platformdirs=3.1.1
  - pooch=1.7.0
  - portaudio=19.6.0
  - pre-commit=3.1.1
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio=16.1
  - pure_eval=0.2.2
  - pyaudio=0.2.13
  - pycparser=2.21
  - pycwt=0.3.0a22
  - pygments=2.14.0
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqtgraph=0.13.2
  - pyside6=6.4.2
  - pysocks=1.7.1
  - pysoundfile=0.12.1
  - python=3.10.9
  - python-dateutil=2.8.2
  - python-sounddevice=0.4.1
  - python_abi=3.10
  - pyyaml=6.0
  - qt6-main=6.4.2
  - readline=8.1.2
  - requests=2.28.2
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - setuptools=67.6.0
  - six=1.16.0
  - soxr=0.1.3
  - soxr-python=0.3.3
  - stack_data=0.6.2
  - svt-av1=1.4.1
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - tomli=2.0.1
  - tqdm=4.65.0
  - traitlets=5.9.0
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzdata=2022g
  - ukkonen=1.0.1
  - unicodedata2=15.0.0
  - urllib3=1.26.15
  - virtualenv=20.21.0
  - wcwidth=0.2.6
  - wheel=0.40.0
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.38
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - pyprag==0.0.1
      - pyworld==0.3.2
      - tgt==1.4.4
